# This file generates the GitHub Actions matrix.
# For simple board + shield combinations, add them to the top level board and
# shield arrays, for more control, add individual board + shield combinations
# to the `include` property. You can also use the `cmake-args` property to
# pass flags to the build command, `snippet` to add a Zephyr snippet, and
# `artifact-name` to assign a name to distinguish build outputs from each other:
#
---
include:
  # Charybdis without dongle
  - board: nice_nano
    shield: charybdis4x6_left
    artifact-name: charybdis4x6_left
  - board: nice_nano
    shield: charybdis4x6_right
    artifact-name: charybdis4x6_right
  - board: nice_nano
    shield: charybdis4x6_right
    artifact-name: charybdis4x6_right_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  # Charybdis with dongle
  - board: nice_nano
    shield: charybdis4x6_right_periph
    artifact-name: charybdis4x6_right_periph
  - board: nice_nano
    shield: charybdis4x6_dongle
    artifact-name: charybdis4x6_dongle
  - board: nice_nano
    shield: charybdis4x6_dongle
    artifact-name: charybdis4x6_dongle_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y  
  - board: nice_nano
    shield: charybdis4x6_dongle
    artifact-name: charybdis4x6_dongle_logging
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  # sofle_chok without dongle
  - board: nice_nano
    shield: sofle_chok_left
    artifact-name: sofle_chok_left
  - board: nice_nano
    shield: sofle_chok_left
    artifact-name: sofle_chok_left_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
  - board: nice_nano
    shield: sofle_chok_right
    artifact-name: sofle_chok_right
  # sofle_chok with dongle
  - board: nice_nano
    shield: sofle_chok_left_periph
    artifact-name: sofle_chok_left_periph
  - board: nice_nano
    shield: sofle_chok_dongle
    artifact-name: sofle_chok_dongle
  - board: nice_nano
    shield: sofle_chok_dongle
    artifact-name: sofle_chok_dongle_studio
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y  
  - board: nice_nano
    shield: sofle_chok_dongle
    artifact-name: sofle_chok_dongle_logging
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_USB_LOGGING=y
  # - board: nice_nano_v2
  #   shield: charybdis4x6_dongle dongle_screen
  #   artifact-name: charybdis4x6_dongle_sh1107

  # Firmware Reset
  - board: nice_nano
    shield: settings_reset
    format: reset
    artifact-name: reset_nice_nano_v2